// Hotspot definitions positioned relative to forward-facing car (Nose facing +Z, Rear facing -Z)
export const AERO_HOTSPOTS = [
  {
    id: 'front-wing',
    title: 'Active Front Wing',
    subtitle: '3-Element Ground Inlets & Active Flap System',
    pos: [0.0, 0.22, 2.5],
    focusPos: [1.6, 1.0, 4.0],
    lookAt: [0.0, 0.2, 2.2],
    badge: 'AERO // 01',
    stats: { downforce: '34%', dragDelta: '-18% (X-Mode)', regulation: 'Active Aero 2026' },
    lore: 'The 2026 front wing features active dual-flap geometry. In Z-Mode, the flaps pitch up to create front-axle downforce through high-speed turns. In X-Mode, the flaps flatten out to shed drag on straightaways without causing wake turbulence for trailing cars.',
  },
  {
    id: 'halo',
    title: 'Titanium Halo Cockpit',
    subtitle: 'Grade 5 Titanium Safety Cell & Aerodynamic Deflector',
    pos: [0.0, 0.92, 0.2],
    focusPos: [1.6, 1.5, 1.6],
    lookAt: [0.0, 0.8, 0.2],
    badge: 'SAFETY // 02',
    stats: { loadRating: '125 kN', material: 'Ti-6Al-4V', weight: '7.0 kg' },
    lore: 'The Halo safety system withstands a 125-kilonewton vertical and lateral impact (equivalent to two double-decker buses). Its aerodynamically sculpted fairing channels airflow directly into the engine airbox while shielding the driver.',
  },
  {
    id: 'sidepods',
    title: 'Downwash Sidepods',
    subtitle: 'High-Velocity Undercut & Cooling Architecture',
    pos: [0.82, 0.42, 0.4],
    focusPos: [2.4, 1.1, 1.8],
    lookAt: [0.5, 0.4, 0.4],
    badge: 'THERMAL // 03',
    stats: { coolingEfficiency: '98.4%', massFlow: '42 kg/s', packaging: 'Ultra-Compact' },
    lore: 'Extreme undercut geometry guides clean air around the cockpit and pushes it down toward the top of the diffuser. Internal radiator matrix cores cool the 350kW electric battery and 1.6L turbocharged internal combustion engine.',
  },
  {
    id: 'floor',
    title: 'Venturi Underbody Tunnels',
    subtitle: 'Ground Effect Ground Plane & Expansion Diffuser',
    pos: [0.72, 0.1, -0.2],
    focusPos: [2.6, 0.5, 0.8],
    lookAt: [0.3, 0.1, -0.2],
    badge: 'GROUND EFFECT // 04',
    stats: { downforceShare: '48%', rideHeightMin: '25mm', suctionPeak: '4.2 kPa' },
    lore: 'The shaped underbody generates majority downforce via ground effect suction. The 2026 regulations mandate a flat floor center section with twin outer Venturi channels that minimize porpoising while keeping airflow attached through high G corners.',
  },
  {
    id: 'rear-wing',
    title: 'Active Rear Wing & Beam',
    subtitle: 'Dynamic In-Flight Flap System (Replaces DRS)',
    pos: [0.0, 1.05, -2.4],
    focusPos: [1.6, 1.7, -3.6],
    lookAt: [0.0, 0.9, -2.2],
    badge: 'AERO // 05',
    stats: { topSpeedGain: '+28 km/h', actuationTime: '0.12s', dragDrop: '-32%' },
    lore: 'DRS is officially retired for 2026 in favor of a 3-element active rear wing with synchronized lower beam wings. Both the front and rear wings switch automatically into low-drag X-Mode on designated straights for maximum top speed efficiency.',
  },
  {
    id: 'power-unit',
    title: '1.6L V6 Turbo-Hybrid + 350kW MGU-K',
    subtitle: '50/50 Electric & ICE Output (100% Sustainable Fuel)',
    pos: [0.0, 0.75, -0.9],
    focusPos: [2.0, 1.7, -0.6],
    lookAt: [0.0, 0.6, -0.9],
    badge: 'POWERTRAIN // 06',
    stats: { electricPower: '350 kW (475 hp)', icePower: '400 kW (535 hp)', totalOutput: '1,000+ hp' },
    lore: 'The 2026 powertrain achieves near 50/50 power distribution between electric and combustion sources. The MGU-H is eliminated, while the kinetic motor (MGU-K) output triples to 350kW, running exclusively on 100% advanced sustainable drop-in fuel.',
  },
];
