// Comprehensive Formula 1 Circuit Heritage & Technical Lore Database (78 Circuits)
export const circuitBios = {
  adelaide: {
    lore: "A legendary street circuit in Victoria Park that hosted the explosive Australian Grand Prix season finale from 1985 to 1995. Revered by drivers for its unforgiving concrete walls, bumpy high-speed Brabham Straight, and title-deciding drama.",
    type: "Street Circuit",
    turns: 16,
    length: "3.780 km",
    direction: "Clockwise",
  },
  aida: {
    lore: "Nestled in the secluded mountains of Okayama Prefecture, this tight and twisty road course hosted the Pacific Grand Prix in 1994 and 1995, famously dominated by Michael Schumacher's Benetton.",
    type: "Permanent Road Course",
    turns: 13,
    length: "3.703 km",
    direction: "Clockwise",
  },
  'ain-diab': {
    lore: "A fierce coastal road circuit laid out along the Atlantic coast and the Oasis road in Casablanca. It hosted the dramatic 1958 Moroccan Grand Prix that crowned Mike Hawthorn as Britain's first World Champion.",
    type: "Road Circuit",
    turns: 12,
    length: "7.618 km",
    direction: "Clockwise",
  },
  aintree: {
    lore: "Set within the famous Grand National horse racing venue near Liverpool, Aintree hosted five British Grands Prix in the 1950s and 60s, including Stirling Moss's iconic 1955 home triumph for Mercedes.",
    type: "Permanent Road Course",
    turns: 8,
    length: "4.828 km",
    direction: "Clockwise",
  },
  albert_park: {
    lore: "Circumnavigating Melbourne's scenic lake, Albert Park has served as F1's electric season opener since 1996. High-speed chicanes, unpredictable grip, and rapid direction changes make it an unforgiving street-hybrid test.",
    type: "Street-Hybrid Circuit",
    turns: 14,
    length: "5.278 km",
    direction: "Clockwise",
  },
  americas: {
    lore: "Austin's purpose-built amphitheater features a punishing 133-foot climb into an uphill blind Turn 1 hairpin, followed by high-speed flowing esses inspired by Silverstone's Maggotts-Becketts and Hockenheim's Motodrom.",
    type: "Permanent Road Course",
    turns: 20,
    length: "5.513 km",
    direction: "Counter-clockwise",
  },
  anderstorp: {
    lore: "Constructed on an active aircraft runway in the Swedish pine forests, Scandinavian Raceway featured banking, long sweeping turns, and was the site of Niki Lauda's dominant 1978 win in the infamous Brabham BT46B 'Fan Car'.",
    type: "Airfield Road Course",
    turns: 8,
    length: "4.031 km",
    direction: "Clockwise",
  },
  avus: {
    lore: "Consisting of two parallel four-kilometer autobahn straights joined by loops, AVUS featured the terrifying 43-degree brick-paved banking known as the 'Wall of Death', hosting the 1959 German Grand Prix.",
    type: "High-Speed Highway",
    turns: 4,
    length: "8.300 km",
    direction: "Counter-clockwise",
  },
  bahrain: {
    lore: "Designed by Hermann Tilke in the Sakhir desert, Bahrain debuted in 2004 as the Middle East's first Grand Prix. Powerful traction zones, abrasive asphalt, and windblown sand punish rear tires under the floodlights.",
    type: "Permanent Road Course",
    turns: 15,
    length: "5.412 km",
    direction: "Clockwise",
  },
  baku: {
    lore: "A clash of high-speed extremes: modern F1 cars hit 360+ km/h down the 2.2 km Neftchilar Avenue straight before threading through the ultra-narrow 7.6-meter bottleneck around the 12th-century medieval Old City fortress.",
    type: "Street Circuit",
    turns: 20,
    length: "6.003 km",
    direction: "Counter-clockwise",
  },
  boavista: {
    lore: "A treacherous Porto street course featuring cobblestones, tram tracks, and tight harbor corners that hosted the Portuguese Grand Prix in 1958 and 1960, won by Stirling Moss and Jack Brabham.",
    type: "Street Circuit",
    turns: 12,
    length: "7.407 km",
    direction: "Counter-clockwise",
  },
  brands_hatch: {
    lore: "A natural amphitheater in the Kent countryside with dramatic elevation changes, featuring the daunting off-camber drop through Paddock Hill Bend and high-speed swoops through Dingle Dell.",
    type: "Permanent Road Course",
    turns: 9,
    length: "3.703 km",
    direction: "Clockwise",
  },
  bremgarten: {
    lore: "A terrifying forest venue in Bern with sweeping high-speed bends, tree-lined verges, and notorious poor-light conditions through the woods that tested drivers in the 1950–1954 Swiss Grands Prix.",
    type: "Road Circuit",
    turns: 13,
    length: "7.280 km",
    direction: "Clockwise",
  },
  buddh: {
    lore: "An undulating layout in Greater Noida outside New Delhi, celebrated for its climbing multi-apex Turn 10–12 sequence and high-speed sweeps, where Sebastian Vettel achieved three consecutive dominant victories.",
    type: "Permanent Road Course",
    turns: 16,
    length: "5.125 km",
    direction: "Clockwise",
  },
  catalunya: {
    lore: "Barcelona's quintessential test arena. Its mix of long aero-loading sweeps like Turn 3, heavy braking zones, and technical traction sectors provides the definitive evaluation of total chassis balance.",
    type: "Permanent Road Course",
    turns: 14,
    length: "4.657 km",
    direction: "Clockwise",
  },
  charade: {
    lore: "Set around the base of an extinct volcano in the Auvergne mountains, Charade was an 8-kilometer 'Mini-Nürburgring' with over 50 relentless corners and loose volcanic gravel.",
    type: "Mountain Road Course",
    turns: 48,
    length: "8.055 km",
    direction: "Clockwise",
  },
  dallas: {
    lore: "Held in the searing July Texas heat of 1984 around Fair Park, the crumbling tarmac and 40°C heat caused legendary chaos, remembered for Nigel Mansell collapsing while pushing his Lotus across the finish line.",
    type: "Street Circuit",
    turns: 23,
    length: "3.901 km",
    direction: "Counter-clockwise",
  },
  detroit: {
    lore: "A brutally tight downtown street circuit featuring 90-degree corners around the Renaissance Center. Ayrton Senna mastered its unforgiving concrete barriers to score three straight wins from 1986 to 1988.",
    type: "Street Circuit",
    turns: 17,
    length: "4.023 km",
    direction: "Counter-clockwise",
  },
  dijon: {
    lore: "The undulating Dijon-Prenois circuit in Burgundy became motorsport folklore in 1979 thanks to the ferocious wheel-banging battle between Gilles Villeneuve and René Arnoux for second place.",
    type: "Permanent Road Course",
    turns: 8,
    length: "3.801 km",
    direction: "Clockwise",
  },
  donington: {
    lore: "Host of the legendary 1993 European Grand Prix, where Ayrton Senna produced what many call the greatest opening lap in F1 history, overtaking four rivals in torrential rain on Lap 1.",
    type: "Permanent Road Course",
    turns: 12,
    length: "4.020 km",
    direction: "Clockwise",
  },
  essarts: {
    lore: "Rouen-Les-Essarts plunged down through public forests with cobble-lined hairpins and flat-out sweeps down the hill, hosting five French Grands Prix from 1952 to 1968.",
    type: "Road Circuit",
    turns: 9,
    length: "6.542 km",
    direction: "Clockwise",
  },
  estoril: {
    lore: "Overlooking the Atlantic coast, Estoril's long main straight and unending final Parabolica bend saw Ayrton Senna claim his first career Grand Prix victory in pouring rain in 1985.",
    type: "Permanent Road Course",
    turns: 13,
    length: "4.360 km",
    direction: "Clockwise",
  },
  fuji: {
    lore: "Situated at the foot of Mount Fuji with an immense 1.5-kilometer main straight, Fuji hosted the fateful 1976 season showdown between James Hunt and Niki Lauda in treacherous torrential rain.",
    type: "Permanent Road Course",
    turns: 16,
    length: "4.563 km",
    direction: "Clockwise",
  },
  galvez: {
    lore: "Buenos Aires' Autódromo Oscar y Juan Gálvez hosted 20 Argentine Grands Prix across multiple technical permutations, celebrated for Juan Manuel Fangio's home victories in the 1950s.",
    type: "Permanent Road Course",
    turns: 15,
    length: "4.259 km",
    direction: "Clockwise",
  },
  george: {
    lore: "The Prince George Circuit in East London, South Africa, swept along the Indian Ocean coastline, hosting three World Championship rounds in the 1960s with Jim Clark winning in 1962 and 1965.",
    type: "Coastal Road Course",
    turns: 8,
    length: "3.920 km",
    direction: "Clockwise",
  },
  hockenheimring: {
    lore: "Originally a lightning-fast blast through the dense German forest with slipstreaming chicanes, Hockenheim was redesigned in 2002 into a technical arena crowned by the atmospheric Motodrom stadium section.",
    type: "Permanent Road Course",
    turns: 17,
    length: "4.574 km",
    direction: "Clockwise",
  },
  hungaroring: {
    lore: "F1's first venture behind the Iron Curtain in 1986. Often dubbed 'Monaco without walls', the dusty valley circuit demands maximum aerodynamic downforce and relentless driver rhythm.",
    type: "Permanent Road Course",
    turns: 14,
    length: "4.381 km",
    direction: "Clockwise",
  },
  imola: {
    lore: "Named after Enzo and Dino Ferrari, this high-speed temple through Emilia-Romagna features the legendary Tamburello, Acque Minerali, and Rivazza complexes, steeped in deep Tifosi passion and motorsport emotion.",
    type: "Permanent Road Course",
    turns: 19,
    length: "4.909 km",
    direction: "Counter-clockwise",
  },
  indianapolis: {
    lore: "Combining the iconic banked oval Turn 1 and a technical infield section, IMS brought Formula 1 to the 'Brickyard' from 2000 to 2007, marked by Michael Schumacher's five victories.",
    type: "Road-Oval Hybrid",
    turns: 13,
    length: "4.192 km",
    direction: "Clockwise",
  },
  interlagos: {
    lore: "A natural amphitheater in São Paulo with anti-clockwise elevation plunges, the Senna S, and high-speed sweeps onto the main straight, renowned for delivering chaotic, championship-deciding rain races.",
    type: "Permanent Road Course",
    turns: 15,
    length: "4.309 km",
    direction: "Counter-clockwise",
  },
  istanbul: {
    lore: "Tilke's masterwork, famous worldwide for the quadruple-apex, multi-G Turn 8 that tests driver neck muscles and tire load to the absolute limit across rolling Anatolian terrain.",
    type: "Permanent Road Course",
    turns: 14,
    length: "5.338 km",
    direction: "Counter-clockwise",
  },
  jacarepagua: {
    lore: "The Autódromo Internacional Nelson Piquet in Rio de Janeiro hosted the Brazilian Grand Prix through the 1980s under sweltering tropical heat, framed by scenic coastal lagoons and mountains.",
    type: "Permanent Road Course",
    turns: 11,
    length: "5.031 km",
    direction: "Counter-clockwise",
  },
  jarama: {
    lore: "A tight, technical venue north of Madrid designed by John Hugenholtz, famous for Gilles Villeneuve's masterclass in 1981 where he held off four faster cars in a train across the entire race.",
    type: "Permanent Road Course",
    turns: 11,
    length: "3.404 km",
    direction: "Clockwise",
  },
  jeddah: {
    lore: "The fastest street circuit in Formula 1 history, running along the Red Sea Corniche with average speeds exceeding 250 km/h through blind, high-speed walled esses and banked sweeps.",
    type: "High-Speed Street Circuit",
    turns: 27,
    length: "6.174 km",
    direction: "Counter-clockwise",
  },
  jerez: {
    lore: "Located in the sun-drenched Andalusian hills, Jerez hosted the dramatic 1997 season finale where Jacques Villeneuve clashed with Michael Schumacher to claim the World Championship.",
    type: "Permanent Road Course",
    turns: 13,
    length: "4.428 km",
    direction: "Clockwise",
  },
  kyalami: {
    lore: "Set at high altitude north of Johannesburg, Kyalami's thin air punished engines and created ferocious slipstreaming battles along the main straight through the 1960s to 1980s.",
    type: "Permanent Road Course",
    turns: 13,
    length: "4.261 km",
    direction: "Anti-clockwise",
  },
  las_vegas: {
    lore: "The dazzling 6.2 km Strip Circuit races straight down the iconic Las Vegas Boulevard under neon lights, reaching top speeds of 350 km/h with low grip and cold desert night temperatures.",
    type: "Night Street Circuit",
    turns: 17,
    length: "6.201 km",
    direction: "Counter-clockwise",
  },
  lemans: {
    lore: "The Bugatti Circuit at Le Mans, using portions of the legendary 24 Hours circuit including the Dunlop Chicane, hosted the 1967 French Grand Prix won by Jack Brabham.",
    type: "Permanent Road Course",
    turns: 14,
    length: "4.422 km",
    direction: "Clockwise",
  },
  long_beach: {
    lore: "The 'Monaco of the United States' threaded around palm trees and the Pacific Ocean shoreline, remembered for John Watson's incredible 1983 victory from 22nd on the starting grid.",
    type: "Street Circuit",
    turns: 11,
    length: "3.275 km",
    direction: "Clockwise",
  },
  losail: {
    lore: "Qatar's fast, flowing night track demands relentless medium- and high-speed commitment with smooth asphalt and high tire energy loading through its 16 continuous radius turns.",
    type: "Permanent Night Circuit",
    turns: 16,
    length: "5.419 km",
    direction: "Clockwise",
  },
  madring: {
    lore: "Debuting on the 2026 calendar, this cutting-edge hybrid street venue connects the IFEMA exhibition complex with Madrid's urban center, incorporating a banked curve and high-speed tunnel run.",
    type: "Hybrid Street Circuit",
    turns: 20,
    length: "5.474 km",
    direction: "Clockwise",
  },
  magny_cours: {
    lore: "Nestled in rural Burgundy, Magny-Cours recreated famous corners from around the world (Estoril, Imola chicanes, Adelaide hairpin) on an ultra-smooth, high-precision asphalt surface.",
    type: "Permanent Road Course",
    turns: 17,
    length: "4.411 km",
    direction: "Clockwise",
  },
  marina_bay: {
    lore: "The original F1 night race, Marina Bay is a grueling test of human endurance under Singapore's stifling humidity, with 19 tight corners flanked by unforgiving concrete barriers.",
    type: "Night Street Circuit",
    turns: 19,
    length: "4.940 km",
    direction: "Counter-clockwise",
  },
  miami: {
    lore: "Built around Hard Rock Stadium in Miami Gardens, the circuit combines high-speed flowing sweeps, a tight chicane under the turnpike overpasses, and long top-speed DRS straights.",
    type: "Hybrid Street Circuit",
    turns: 19,
    length: "5.412 km",
    direction: "Counter-clockwise",
  },
  monaco: {
    lore: "The crown jewel of Formula 1. An unchanged, historic jewel around the Principality's harbor, Casino Square, and Grand Hotel Hairpin where millimeter precision separates triumph from disaster.",
    type: "Street Circuit",
    turns: 19,
    length: "3.337 km",
    direction: "Clockwise",
  },
  monsanto: {
    lore: "A winding parkland road circuit located within the Monsanto Forest Park in Lisbon, hosting the 1959 Portuguese Grand Prix over varying surfaces and tram lines.",
    type: "Park Road Course",
    turns: 9,
    length: "5.440 km",
    direction: "Clockwise",
  },
  montjuic: {
    lore: "A thrilling, undulating street track on Barcelona's Montjuïc mountain, weaving past ancient palaces and parks with steep downhill brake zones that terrified and captivated drivers in the 1970s.",
    type: "Street Circuit",
    turns: 12,
    length: "3.791 km",
    direction: "Counter-clockwise",
  },
  monza: {
    lore: "The 'Temple of Speed'. F1's fastest and most historic cathedral, where cars race at full throttle for 80% of the lap down the Rettifilo, Variante Ascari, and the hallowed Curva Parabolica.",
    type: "High-Speed Cathedral",
    turns: 11,
    length: "5.793 km",
    direction: "Clockwise",
  },
  mosport: {
    lore: "Canada's historic undulating road circuit northeast of Toronto, celebrated for its plunging blind crests, heavy elevation shifts, and the high-speed sweep of Moss Corner.",
    type: "Permanent Road Course",
    turns: 10,
    length: "3.957 km",
    direction: "Clockwise",
  },
  mugello: {
    lore: "Owned by Ferrari in the Tuscan hills, Mugello is an ultra-fast roller coaster with blinding high-speed change of directions through Casanova-Savelli and the flat-out Arrabbiata 1 & 2 sweeps.",
    type: "Permanent Road Course",
    turns: 15,
    length: "5.245 km",
    direction: "Clockwise",
  },
  nivelles: {
    lore: "A modern, open European road course south of Brussels that hosted two Belgian Grands Prix in 1972 and 1974, both won by Emerson Fittipaldi.",
    type: "Permanent Road Course",
    turns: 8,
    length: "3.724 km",
    direction: "Clockwise",
  },
  nurburgring: {
    lore: "From the legendary 22.8 km 'Green Hell' (Nordschleife) to the modernized Grand Prix-Strecke, the Eifel mountains venue represents the pinnacle of motorsport challenge and unpredictable weather.",
    type: "Permanent Road Course",
    turns: 15,
    length: "5.148 km",
    direction: "Clockwise",
  },
  okayama: {
    lore: "Formerly known as TI Circuit Aida, this secluded technical circuit in the Okayama mountains tested chassis agility and mechanical grip during the 1994 and 1995 Pacific Grands Prix.",
    type: "Permanent Road Course",
    turns: 13,
    length: "3.703 km",
    direction: "Clockwise",
  },
  pedralbes: {
    lore: "A wide urban street circuit in the Pedralbes neighborhood of Barcelona with huge boulevards, hosting the 1951 and 1954 Spanish Grands Prix where Fangio took his maiden title.",
    type: "Street Circuit",
    turns: 6,
    length: "6.316 km",
    direction: "Clockwise",
  },
  pescara: {
    lore: "The longest circuit in Formula 1 World Championship history at 25.8 km, winding through Italian coastal villages, mountain passes, and a four-mile flat-out straight down to the Adriatic Sea.",
    type: "Public Road Circuit",
    turns: 28,
    length: "25.800 km",
    direction: "Clockwise",
  },
  phoenix: {
    lore: "A grid-patterned downtown Arizona street circuit known for its dusty 90-degree corners, remembered for Jean Alesi's daring duel with Ayrton Senna in 1990.",
    type: "Street Circuit",
    turns: 15,
    length: "3.798 km",
    direction: "Counter-clockwise",
  },
  portimao: {
    lore: "The Algarve International Circuit is a modern roller-coaster with massive blind crests, plunging downhill braking zones, and sweeping parabolicas that challenge driver courage.",
    type: "Permanent Road Course",
    turns: 15,
    length: "4.653 km",
    direction: "Clockwise",
  },
  red_bull_ring: {
    lore: "Nestled in the Styrian Alps, the Red Bull Ring is a short, punchy power circuit featuring heavy uphill braking zones into Turn 1 and 3 followed by fast, downhill downhill sweeps.",
    type: "Alpine Road Course",
    turns: 10,
    length: "4.318 km",
    direction: "Clockwise",
  },
  reims: {
    lore: "A high-speed triangular road circuit in the Champagne countryside where cars slipstreamed past grandstands and wheat fields at extreme velocity in the 1950s and 60s.",
    type: "High-Speed Road Circuit",
    turns: 6,
    length: "8.302 km",
    direction: "Clockwise",
  },
  ricard: {
    lore: "Perched on the Castellet plateau, Paul Ricard features the iconic 1.8 km Mistral Straight, Signes flat-out corner, and distinctive blue and red high-friction run-off zones.",
    type: "Permanent Road Course",
    turns: 15,
    length: "5.842 km",
    direction: "Clockwise",
  },
  riverside: {
    lore: "A rugged Californian road course situated in the desert hills east of Los Angeles, hosting the 1960 US Grand Prix won by Stirling Moss in a Lotus-Climax.",
    type: "Permanent Road Course",
    turns: 9,
    length: "5.271 km",
    direction: "Clockwise",
  },
  rodriguez: {
    lore: "Located 2,200 meters above sea level in Mexico City, the thin air reduces engine power and downforce while cars blast down the long straight into the roaring Foro Sol stadium section.",
    type: "High-Altitude Road Course",
    turns: 17,
    length: "4.304 km",
    direction: "Clockwise",
  },
  sebring: {
    lore: "A bumpy airfield circuit in central Florida that hosted the inaugural United States Grand Prix in 1959, famous for Jack Brabham pushing his Cooper across the line to win the title.",
    type: "Airfield Road Course",
    turns: 17,
    length: "8.369 km",
    direction: "Clockwise",
  },
  sepang: {
    lore: "Designed by Hermann Tilke and opened in 1999, Sepang set the benchmark for modern F1 circuits with wide sweeping high-speed corners, oppressive heat, and back-to-back 900m grandstand straights.",
    type: "Permanent Road Course",
    turns: 15,
    length: "5.543 km",
    direction: "Clockwise",
  },
  shanghai: {
    lore: "Modeled after the Chinese character 'Shang' (上), this state-of-the-art facility features the tightening 270-degree Turn 1–2 vortex and an immense 1.2-kilometer back straight.",
    type: "Permanent Road Course",
    turns: 16,
    length: "5.451 km",
    direction: "Clockwise",
  },
  silverstone: {
    lore: "The birthplace of Formula 1 in 1950. A relentless high-speed airfield circuit famous for the iconic Maggotts, Becketts, Chapel, and Copse sequences taken at breathtaking lateral G-forces.",
    type: "High-Speed Heritage Course",
    turns: 18,
    length: "5.891 km",
    direction: "Clockwise",
  },
  sochi: {
    lore: "Winding around the Olympic Park venues on the Black Sea coast, Sochi Autodrom featured smooth asphalt and the unending, high-load 180-degree Turn 3 left-hander.",
    type: "Olympic Street Circuit",
    turns: 18,
    length: "5.848 km",
    direction: "Clockwise",
  },
  spa: {
    lore: "The ultimate driver's circuit in the Ardennes forest. Spanning 7 km of extreme elevation changes, Eau Rouge-Raidillon, Pouhon, and Blanchimont with notoriously unpredictable microclimates.",
    type: "Ardennes Rollercoaster",
    turns: 19,
    length: "7.004 km",
    direction: "Clockwise",
  },
  suzuka: {
    lore: "F1's only figure-eight circuit, crafted by John Hugenholtz. The rapid Esses, Degner corners, Spoon curve, and flat-out 130R make it universally adored by drivers worldwide.",
    type: "Figure-Eight Road Course",
    turns: 18,
    length: "5.807 km",
    direction: "Clockwise",
  },
  tremblant: {
    lore: "A scenic, undulating road circuit in the Laurentian Mountains northwest of Montreal that hosted the Canadian Grand Prix in 1968 and 1970.",
    type: "Mountain Road Course",
    turns: 15,
    length: "4.265 km",
    direction: "Clockwise",
  },
  valencia: {
    lore: "A sleek Mediterranean harbor circuit in Spain crossing a swing bridge over the marina, hosting European Grands Prix from 2008 to 2012, crowned by Alonso's emotional 2012 victory.",
    type: "Harbor Street Circuit",
    turns: 25,
    length: "5.419 km",
    direction: "Clockwise",
  },
  vegas: {
    lore: "Laid out in the parking lot of Caesars Palace in 1981 and 1982, this anti-clockwise desert track was a grueling, neck-straining physical ordeal that crowned Nelson Piquet and Keke Rosberg.",
    type: "Flat Street Circuit",
    turns: 14,
    length: "3.650 km",
    direction: "Counter-clockwise",
  },
  villeneuve: {
    lore: "Set on Île Notre-Dame in Montreal, this stop-and-go blast along the Saint Lawrence Seaway features heavy braking chicanes, hairpins, and the infamous 'Wall of Champions'.",
    type: "Island Hybrid Circuit",
    turns: 14,
    length: "4.361 km",
    direction: "Clockwise",
  },
  watkins_glen: {
    lore: "The spiritual home of the US Grand Prix in upstate New York, revered for its sweeping esses, the high-speed 'Boot' section, and vibrant autumn festival atmosphere in the 1960s and 70s.",
    type: "Historic Road Course",
    turns: 11,
    length: "5.430 km",
    direction: "Clockwise",
  },
  yas_marina: {
    lore: "Abu Dhabi's multi-billion dollar twilight spectacle featuring a tunnel pit exit, hotel fly-through, and modernized sweeping banked hairpins for the season finale under the setting sun.",
    type: "Twilight Harbor Circuit",
    turns: 16,
    length: "5.281 km",
    direction: "Counter-clockwise",
  },
  yeongam: {
    lore: "The Korean International Circuit featured a high-speed blast with a 1.2 km straight in Sector 1 transitioning into a tight marina street-style complex in Sector 3.",
    type: "Hybrid Road Course",
    turns: 18,
    length: "5.615 km",
    direction: "Counter-clockwise",
  },
  zandvoort: {
    lore: "Rolling through the coastal sand dunes on the North Sea, Zandvoort blends old-school courage with modern 18-degree banking at Hugenholtz and Arie Luyendyk bocht.",
    type: "Banked Dune Circuit",
    turns: 14,
    length: "4.259 km",
    direction: "Clockwise",
  },
  zeltweg: {
    lore: "An abrasive L-shaped airfield course on the Zeltweg military air base that hosted the 1964 Austrian Grand Prix won by Lorenzo Bandini in a Ferrari.",
    type: "Airfield Circuit",
    turns: 4,
    length: "3.200 km",
    direction: "Clockwise",
  },
  zolder: {
    lore: "Set in the pine forests of Flanders, Circuit Zolder hosted ten Belgian Grands Prix through the 1970s and 80s, demanding heavy braking through chicanes and hairpins.",
    type: "Permanent Road Course",
    turns: 10,
    length: "4.262 km",
    direction: "Clockwise",
  },
};
