export const circuitMap = {
  adelaide: 'Adelaide_(long_route).svg',
  'ain-diab': 'Ain-Diab.svg',
  aintree: 'Circuit_Aintree.svg',
  albert_park: 'Albert_Park_Circuit.svg',
  americas: 'F1 circuits 2014-2018 - Circuit of the Americas (version 2).svg',
  anderstorp: 'Scandinavian Raceway Anderstorp.svg',
  avus: 'Circuit AVUS.svg',
  bahrain: 'Bahrain International Circuit--Paddock Circuit.svg',
  baku: 'F1 circuits 2014-2018 - Baku City Circuit (version 2).svg',
  boavista: 'Boavista (Oporto) 1958.svg',
  brands_hatch: 'Brands_Hatch.svg',
  bremgarten: 'Circuit Bremgarten.svg',
  buddh: 'Buddh International Circuit.svg',
  catalunya: 'Formula1 Circuit Catalunya 2021.svg',
  charade: 'Circuit Charade 1958 1988.png',
  dallas: 'Circuit Fair Park Dallas.svg',
  detroit: 'Downtown Detroit Street Circuit.svg',
  dijon: 'Circuit de Dijon-Prenois-1972.svg',
  donington: 'Donington_circuit.svg',
  essarts: 'Rouen-Les-Essarts.svg',
  estoril: 'Estoril track map.svg',
  fuji: 'Fuji Speedway (1965-1974 Layout).svg',
  hockenheimring: 'Circuit Hockenheimring-2002.svg',
  indianapolis: 'Indianapolis Motor Speedway - road course.svg',
  jarama: 'Circuito Permanente del Jarama.svg',
  jerez: 'Circuito de Jerez (1985-1992).svg',
  las_vegas: '2023 Las Vegas street circuit.svg',
  lemans: 'Circuit Sarthe.svg',
  long_beach: 'Long Beach (1984-86) compat.svg',
  madring: 'Madring (2026).svg',
  magny_cours: 'Circuit de Nevers Magny-Cours (1992-2002).svg',
  miami: '2022 F1 CourseLayout Miami.svg',
  monsanto: 'Circuit Monsanto.png',
  montjuic: 'Montjuïc circuit.svg',
  nurburgring: 'Nürburgring - Grand-Prix-Strecke.svg',
  pedralbes: 'Circuit Pedralbes.png',
  phoenix: 'Phoenix Grand Prix Route - 1989, 1990.svg',
  portimao: 'Autódromo do Algarve F1 Sectors.svg',
  reims: 'Circuit Reims-Gueux.png',
  ricard: 'F1 circuits 2014-2018 - Paul Ricard Circuit (version 2).svg',
  riverside: 'Riverside International Raceway 1980.svg',
  sebring: 'Sebring International Raceway.svg',
  silverstone: 'Circuit Silverstone 2010 infobox.svg',
  valencia: 'Valencia (Ricardo Tormo) track map.svg',
  vegas: 'Caesars Palace Indy circuit 1983.svg',
  watkins_glen: 'Watkins Glen International Long Circuit 2024.svg',
};